(deffacts guests
  #S(guest :name n1 :sex m :hobby h3)
  #S(guest :name n1 :sex m :hobby h2)
  #S(guest :name n2 :sex m :hobby h2)
  #S(guest :name n2 :sex m :hobby h3)
  #S(guest :name n3 :sex m :hobby h1)
  #S(guest :name n3 :sex m :hobby h2)
  #S(guest :name n3 :sex m :hobby h3)
  #S(guest :name n4 :sex f :hobby h3)
  #S(guest :name n4 :sex f :hobby h2)
  #S(guest :name n5 :sex f :hobby h1)
  #S(guest :name n5 :sex f :hobby h2)
  #S(guest :name n5 :sex f :hobby h3)
  #S(guest :name n6 :sex f :hobby h3)
  #S(guest :name n6 :sex f :hobby h1)
  #S(guest :name n6 :sex f :hobby h2)
  #S(guest :name n7 :sex f :hobby h3)
  #S(guest :name n7 :sex f :hobby h2)
  #S(guest :name n8 :sex m :hobby h3)
  #S(guest :name n8 :sex m :hobby h1)
  #S(last_seat :seat 8)
  #S(count :c 1)
  #S(context :state start))
