(deffacts guests
  #S(guest :name n1 :sex m :hobby h3)
  #S(guest :name n1 :sex m :hobby h2)
  #S(guest :name n2 :sex m :hobby h1)
  #S(guest :name n2 :sex m :hobby h2)
  #S(guest :name n2 :sex m :hobby h3)
  #S(guest :name n3 :sex f :hobby h3)
  #S(guest :name n3 :sex f :hobby h2)
  #S(guest :name n4 :sex f :hobby h1)
  #S(guest :name n4 :sex f :hobby h2)
  #S(guest :name n4 :sex f :hobby h3)
  #S(last_seat :seat 4)
  #S(count :c 1)
  #S(context :state start))
